repos:
-   repo: https://github.com/urlstechie/urlchecker-python
    rev: test-pre-commit
    hooks:
    -   id: urlchecker-check
#        additional_dependencies: [urlchecker>=0.0.30]
        args: ['check', '.']
